spring:
  jpa:
    hibernate:
      ddl-auto: validate # 개발 시에는 validate 하고, 개발이 끝나면 create 변경 후 생성된 스키마를 복사해서 schema.bak 로 작성해서 사용
    generate-ddl: false
    show-sql: true
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: psyoblade
    password: pass
    hikari:
      maximum-pool-size: 5
#    platform: postgresql --> 와 같이 작성하면 resources/schema-postgresql.sql 파일을 지정할 수 있습니다.