# standard out jpa queries
spring:
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  h2:
    console:
      enabled: true

# out jpa queries via logging - ERROR, WARN, INFO, DEBUG, TRACE
logging.level.org.hibernate:
  SQL: INFO
  type.descriptor.sql.BasicBinder: INFO
