spring:
#  jpa: -- remove standard out jpa queries
#    show-sql: true
#    properties.hibernate.format_sql: true
  h2:
    console:
      enabled: true

# out jpa queries via logging
logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE
