/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.suhyuk.spring.board;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class BoardApplicationTest {

    @Autowired
    private SqlSessionTemplate sqlSession;

    @Test
    public void testSqlSession() throws Exception {
        System.out.println(sqlSession.toString());
    }
}
